confirm-before-quit = false

[renderer]
backend = "Webgpu"
custom-shader = [
  "@yazelix_terminal_shader_dir@/cursor_trail_dusk.glsl",
  "@yazelix_terminal_shader_dir@/generated_effects/sweep.glsl",
  "@yazelix_terminal_shader_dir@/generated_effects/rectangle_boom.glsl",
]

[window]
decorations = "Disabled"

[effects]
trail-cursor = true

[fonts]
family = "cascadiacode"
size = 18.0
additional-dirs = [
  "@yazelix_terminal_font_dir@",
  "@yazelix_terminal_emoji_font_dir@",
]
symbol-map = [
  { start = "E000", end = "F900", font-family = "Symbols Nerd Font Mono" },
  { start = "F0001", end = "F1AF1", font-family = "Symbols Nerd Font Mono" },
  { start = "1F000", end = "1FB00", font-family = "Noto Color Emoji" },
]
